[package]
name = "klad"
version = "0.5.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
encoding_rs = "0.8"
chardetng = "0.1"
typst = "0.15.1"
typst-assets = { version = "0.15.1", features = ["fonts"] }
typst-svg = "0.15.1"
typst-layout = "0.15.1"

[profile.release]
strip = true
lto = true
